version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image:
- Visual Studio 2017
- Previous Visual Studio 2017
configuration:
- Debug
- Release
- Mixed
platform:
- x64
- x86
before_build:
- cmd: git submodule update --init --recursive
build:
  project: src/engine.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: xrbuild.cmd
test: off
artifacts:
- path: res/xdOpenXRay.Dx86.7z
  name: xdOpenXRay.Dx86.7z
- path: res/xdOpenXRay.Dx64.7z
  name: xdOpenXRay.Dx64.7z
- path: res/xdOpenXRay.Mx86.7z
  name: xdOpenXRay.Mx86.7z
- path: res/xdOpenXRay.Mx64.7z
  name: xdOpenXRay.Mx64.7z
- path: res/xdOpenXRay.Rx86.7z
  name: xdOpenXRay.Rx86.7z
- path: res/xdOpenXRay.Rx64.7z
  name: xdOpenXRay.Rx64.7z
deploy:
- provider: GitHub
  tag: xd$(appveyor_build_version)
  release: xdOpenXRay (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: UAusA7Nky/sPD8phs1KqV7T0FipjuVgYIioj41JnPjYAX7HMPGe293sdXYM0qjPd
  artifact: xdOpenXRay.Dx86.7z, xdOpenXRay.Dx64.7z, xdOpenXRay.Mx86.7z, xdOpenXRay.Mx64.7z, xdOpenXRay.Rx86.7z, xdOpenXRay.Rx64.7z
  draft: true
  force_update: true