version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image:
- Visual Studio 2017
configuration:
- Mixed
- Release
- Mixed_COC
- Release_COC
platform:
- x64
- x86
before_build:
- cmd: git submodule update --init --recursive
build:
  project: src/engine.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: xrbuild.cmd
test: off
artifacts:
- path: res/OpenXRay.Mx86.7z
  name: OpenXRay.Mx86.7z
- path: res/OpenXRay.Mx64.7z
  name: OpenXRay.Mx64.7z
- path: res/OpenXRay.Rx86.7z
  name: OpenXRay.Rx86.7z
- path: res/OpenXRay.Rx64.7z
  name: OpenXRay.Rx64.7z
- path: res/OpenXRay_CoC.Mx86.7z
  name: OpenXRay_CoC.Mx86.7z
- path: res/OpenXRay_CoC.Mx64.7z
  name: OpenXRay_CoC.Mx64.7z
- path: res/OpenXRay_CoC.Rx86.7z
  name: OpenXRay_CoC.Rx86.7z
- path: res/OpenXRay_CoC.Rx64.7z
  name: OpenXRay_CoC.Rx64.7z
deploy:
- provider: GitHub
  tag: OXR_CoC$(appveyor_build_version)
  release: OXR_CoC (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: 9iDOYVjThQ3nK0u2621weCBYrqi7YZgoE9p1AJ3JHn+hJtlQN/kxE9ccC/EDqHxa
  artifact: OpenXRay.Mx86.7z, OpenXRay.Mx64.7z, OpenXRay.Rx86.7z, OpenXRay.Rx64.7z, OpenXRay_CoC.Mx86.7z, OpenXRay_CoC.Mx64.7z, OpenXRay_CoC.Rx86.7z, OpenXRay_CoC.Rx64.7z
  draft: true
  force_update: true